### ISSUE TITLE
src/tink/Template.hx:22: characters 2-25 : Class<tink.MacroApi> has no field onTypeNotFound (Suggestion: typeNotFound)

### ISSUE THREAD

**Issue by as3boyan** [haxetink/tink_template#1]
haxe tink_template.hxml 
src/tink/Template.hx:22: characters 2-25 : Class<tink.MacroApi> has no field onTypeNotFound (Suggestion: typeNotFound)
Class not found : Example

**Comment by as3boyan** [comment]
I don't understand how to get started using this library

**Comment by back2dos** [comment]
Uhm, I think this should no longer be an issue.
