### ISSUE TITLE
How to use functions 

### ISSUE THREAD

**Issue by markknol** [haxetink/tink_template#14]
```haxe
  ${ var arr = [] }
  ${ for chord in chords }
    ${ var name = chord.toString() }
    ${ if (map.indexOf(name) == -1) }
        ${ arr.push(name) }
        <h1>${name}</h1>
    ${end}
  ${end}
```
> I use `--macro tink.Template.addFlavor("html", "${", "}", false)` for the nice interpolated string feeling

I have these questions:

1.  `${ arr.push(name) }` prints a number in the template. How do I prevent that?
1. Probably related question; I tried to use some functions that don't return something (for example `${ map.insert(0, name) }`, but then I get `cannot use Void as value`. How to deal with that?

Using Haxe 4.0.0 Preview 5

**Comment by markknol** [comment]
The workaround I just start using in meanwhile is `<!-- ${ arr.push(name) } -->`

**Comment by back2dos** [comment]
https://github.com/haxetink/tink_template#not-outputting ;)

**Comment by markknol** [comment]
Thanks! Didn't see that.
