### ISSUE TITLE
-D tink_template_pos=on doesn't work with haxe 4 rc1

### ISSUE THREAD

**Issue by filt3rek** [haxetink/tink_template#15]
Hej !

As the title of the issue suggest, -D tink_template_pos=on doesn't work with haxe 4 previews neither with rc1.
It always tells line 1.

**Comment by kevinresol** [comment]
how is the situation in rc2?

**Comment by filt3rek** [comment]
Hej Kevin !

Still the same for me with RC2 :/

**Comment by filt3rek** [comment]
Hej !

I've reported the issue on the Haxe compiler github as @back2dos suggested, but I can't reproduce the case when it worked. I don't know anymore if something maybe changed in tink_template since ?

https://github.com/HaxeFoundation/haxe/issues/9336

I'm sure it worked one day, we get the right line number in the template where there was an error, and now I can't reproduce that.
Can anyone help me please ?
I work for monthes now with that issue not knowing who can at the end fix that, it could be good if we fix that once.

Thanks

**Comment by filt3rek** [comment]
Hej Juraj !

Is there any improvements to the position in the template files please ?
It still seems to not working :(

**Comment by back2dos** [comment]
Fixed in 0.4.2.
