### ISSUE TITLE
[feature] switch off position comments in debug mode

### ISSUE THREAD

**Issue by AdrianV** [haxetink/tink_template#2]
when using tink_templates together with other JS frameworks, the comments are sometimes hindering because they have no style - if that frameworks wrongly expects that every DOM element has a style, the code breaks in debug mode and works in release mode. with an additional flag the comment generation could be turned off.

**Comment by back2dos** [comment]
See here: https://github.com/haxetink/tink_template#position-comments

**Comment by AdrianV** [comment]
thanks great !
