### ISSUE TITLE
fails to compile with Haxe head

### ISSUE THREAD

**Issue by AdrianV** [haxetink/tink_template#6]
I got an error during compilation:
/tink/template/Generator.hx:189: characters 6-15 : haxe.macro.Field has no field publish

**Comment by back2dos** [comment]
The fix for https://github.com/HaxeFoundation/haxe/issues/5888 broke it. Thanks for reporting ;)

**Comment by AdrianV** [comment]
ah - I couldn't figure out whats wrong
