### ISSUE TITLE
does not work with haxe development anymore

### ISSUE THREAD

**Issue by AdrianV** [haxetink/tink_template#7]
Since haxe commit 105387ff3301d21bcc45ed06358c6ef4d705868b "Inline constructors rework"
my templates wont compile anymore. I get an error "Cannot use this expression as value" at random places. This is not exactly an issue with tink_templates, but I can't find the reason for this.

**Comment by AdrianV** [comment]
I found a "reason" for this - templates that do not end with CR LF in the last line fail to compile. Strange that it worked before.

**Comment by back2dos** [comment]
Sorry, this somehow got lost. I do intend to fix it ;)

**Comment by AdrianV** [comment]
I haven't any problems recently, but I will check again

**Comment by back2dos** [comment]
Hmm, ok, unless this occurs again, let's consider it resolved ^^
