### ISSUE TITLE
Haxe 4 Cannot use Void as value

### ISSUE THREAD

**Issue by filt3rek** [haxetink/tink_template#9]
Hej Juraj,

I tried Haxe 4 with my templates which work great using Haxe 3.4.7 and I get this error "Cannot use Void as value" when doing a simple test : 
`::if Server.isPopup::`
The strange thing is that there is another test (the same one) upper in my template and it doesn't throw any error.

**Comment by filt3rek** [comment]
If I add an `::else::` statement, it works fine.
But I still don't understand why my first test upper in my template and without any `::else::` works fine too and doesn't throw any error.

**Comment by kevinresol** [comment]
Can you post a reproducible code snippet or something?

**Comment by filt3rek** [comment]
Hej,
Thanks for your answer.
Of course : 
```
<div>
	blabla
</div>
::if Server.isPopup::
<div>
	blabla
</div>
::end::
```

**Comment by filt3rek** [comment]
Here that works fine :
```
<div>
	blabla
</div>
::if Server.isPopup::
<div>
	blabla
</div>
::else::
::end::
```

**Comment by filt3rek** [comment]
Hej there !

Has anyone seen why my sample dosn't work please ?

Regards,
